name: flutter_calculator
description: Flutter Calculator

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 "

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  math_expressions: ^2.3.0
  get:
  google_fonts: ^6.1.0
  flutter_advanced_switch: ^3.0.1
  hive: ^2.2.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:

    

